### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by fanatos123** [seyedhojjathosseini/sqlmap-AutoTamper#1]
perceives __init__.py as tamper and falls

**Comment by seyedhojjathosseini** [comment]
Yes I know
But that doesn't matter
If you have Python capability, you can edit
This script is for example only
You can give it more functionality

**Comment by AhrimanSefid** [comment]
Hi.
Send Me Error :
$ auto.py
  File "H:\sqlmap-1.6\auto.py", line 14
    print "Your Tamper is: "+ entry
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Your Tamper is: "+ entry)?

**Comment by seyedhojjathosseini** [comment]
> Hi.
> Send Me Error :
> $ auto.py
> File "H:\sqlmap-1.6\auto.py", line 14
> print "Your Tamper is: "+ entry
> ^
> SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Your Tamper is: "+ entry)?

![python2 auto py](https://user-images.githubusercontent.com/13599665/86560846-83688c80-bf74-11ea-9032-4e4c8411c085.png)

use python2 or edit code for python3
